services:
  - type: web
    name: hrmsbackend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hrmsBackend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hrmsBackend.settings
